include: package:effective_dart/analysis_options.yaml

linter:
    rules:
      public_member_api_docs: false
      prefer_relative_imports: false
      avoid_catches_without_on_clauses: false
      
      